### ISSUE TITLE
DFRobot Page link Broken

### ISSUE THREAD

**Issue by Chirishman** [LattePandaTeam/Docs#1]
The DFRobot [product page's](https://www.dfrobot.com/product-1404.html) link to your official page is broken 

It links to https instead of HTTP which isn't working. Also something seems to be wrong with your google search result. Clicking on the first result for "lattepanda" on google looks right but redirects me to `http://www.popularselling.com/`

Google Result link text:
`https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwiQgqGLoKvYAhVHON8KHZL1AWAQFgg_MAA&url=http%3A%2F%2Fwww.lattepanda.com%2F&usg=AOvVaw1SY1KTXhNMZPgxq4Y1H5cG`

**Comment by LattePanda** [comment]
Sorry for the late reply. Problem fixed! 
Thanks for your kind remind a lot!

Best,
Lauren
