### ISSUE TITLE
Need recommendation for Battery pack and UPS HAT board for lattepanda V1 in docs and idea for v2 lattepanda

### ISSUE THREAD

**Issue by raghavk92** [LattePandaTeam/Docs#15]
You have provided battery pack recommendations for lattepanda alpha and delta. But you have not provided a recommendation for a power bank for lattepanda v1 with micro usb charging. I really want to use it as a portable device for my purpose . But i dont know which is a reliable power bank for the v1 for that use. Need to use a hdmi display with good resolution (1600x1200) . If you could put a power bank recommendation for the v1 lattepanda in the docs that would be great. And also want an idea to put across the team. I am really waiting for you to put up the next v2 of the original lattepanda with a usb-c charging in it like you have for the more expensive alpha and delta. So they can be easily powered with usb -c charging power banks. And also If you could build a UPS-HAT boards like there are for raspberry pi for the normal lattepanda this would work best for my use case and there would be no problems of power fluctuations and power faliure problems leading to bios corruption. Dont you think the v1 lattepanda should be updated with newer specs and without being so high powered as an alpha . Its already 2019. IF you can build this v2 lattepanda with type c charging , ups HAT board and power bank recommendation it would really solve my problem. I would buy this right now. Even if the combination of it is 150$ or 200$ or even 250$.

If you can fit the lattepanda and hat board within a custom case that would be best. Like nobody has this combination in the x86 world . Only there is this combination in the arm world with  raspberry pi.

If you can come out with a lattepanda which has a built in battery and usb-c charging that would be good also

Please consider making this board.

Thanks

**Comment by chrislattepanda** [comment]
Hi raghavk92, you can use several different usb power banks to power original LattePanda. It is convenient to look up raspberry pi 3 solutions since both consume similar current at 5V. Something like this might work: https://www.adafruit.com/product/1565

**Comment by chrislattepanda** [comment]
Actually, DFRobot has a solution for this. You should be able to use this with a LiPo Battery (with built in protection) and it can work. https://www.dfrobot.com/product-1613.html

**Comment by alphaarea** [comment]
Sorry for the late reply

LattePanda V1, being the first product of LattePanda team, does not take into account the battery power situation.

Because its power consumption is low enough (even lower than the Raspberry Pi 4B), it can be powered by those power banks designed for smart phones easily. A dedicated UPS expansion board would be very expensive instead.

If you need to expand a larger battery, or need to accurately monitor the battery level, you can take @chrislattepanda advice and build your own battery system with a [Battery Fuel Gauge Module](https://www.dfrobot.com/product-1734.html)
