### ISSUE TITLE
BROKEN LINK

### ISSUE THREAD

**Issue by rootorben** [LattePandaTeam/Docs#22]
Ordered a LattePanda, which i should receive in a couple of hours......
So i fired up my jDownloader and downloaded a licensed version of Windows 10 Enterprise 

Now I really want to see how I install the dirt without a brick......

So what do you do as a diehard nerd? 
right, you check the shit on github!

And here is my problem:
The Docs link leads into the empty .....

Either I iron kmspico on the preinstalled unlicensed version OR you give me 
damn again an alternative link to the docs 

Thank you, and best regards......

**Comment by LattePanda** [comment]
Hi rootorben,

Which DOCS link is empty? Could you share this link with us? we will fix it. Sorry for the inconvenience.

**Comment by chrislattepanda** [comment]
Please navigate to this webpage for the full functioning version of the documents
http://docs.lattepanda.com/

Thank you
