### ISSUE TITLE
Alpha dxf/dwg file. Have step, need dxf for accurate mating pcb generation

### ISSUE THREAD

**Issue by rrattinypcbs** [LattePandaTeam/Docs#25]
Hello, 
Working on a Open Source Ventilator using LattePanda Alpha to respond to the COVID-19 crisis. We have the Alpha step file that was uploaded in 2018, we need the dxf file to accurately generate the mating board that will host the sensor and motor control electronics.

With kind regards,
Rob
2020/03/23 11am MST (GMT-6)

**Comment by LattePanda** [comment]
Hi Rob, 
Pls check the link below,
https://github.com/LattePandaTeam/LattePanda-3D-Models/blob/master/LP%20alpha%203D%20Model.zip
