### ISSUE TITLE
Dead Link - example program

### ISSUE THREAD

**Issue by Enginerd27** [LattePandaTeam/Docs#86]
The Physical Programming section has dead links. Both of the first two links in Step 3 of Physical Programming are dead:

http://www.lattepanda.com/wp-content/uploads/2016/02/blinkYourBoard.zip
http://docs.lattepanda.com/content/hardware/examples/

![image](https://user-images.githubusercontent.com/62517320/209904152-12a248b2-574a-4ed5-9532-a191052cc8c8.png)
image snipped from http://docs.lattepanda.com/content/1st_edition/vs_programming/

Context - new customer trying to get started with LattePanda 3 Delta.

**Comment by alphaarea** [comment]
has been fixed by commit [58c364a](https://github.com/LattePandaTeam/Docs/commit/58c364a9e8e77eb9498df28906da283d9ad42b14)
