### ISSUE TITLE
Cannot find Windows 10 disc image file for Sigma

### ISSUE THREAD

**Issue by wappler99** [LattePandaTeam/Docs#88]
Hi guys,
Quick question? Where is the image for Windows 10 for the Sigma? It seems that there is only a Win 11 image. I was expecting to see something similar to the Delta:

![image](https://user-images.githubusercontent.com/16543721/236356876-4552a5a3-9680-49ba-9e98-62089ba0c12e.png)

Thank you!

**Comment by LattePanda** [comment]
Hi,

Pls check the windows installation guide for LattePanda Sigma.
https://docs.lattepanda.com/content/sigma_edition/Operating_Systems/#windows




***@***.***
 Best Regards,


Business Development

LattePanda Team

A: Rm 602, Puruan Bld.,No.2 Boyun Rd, Pudong, Shanghai | 201203 P.R.China

W: www.lattepanda.com<http://www.lattepanda.com/>


From: ***@***.***>
Sent: 2023年5月5日 8:32
To: ***@***.***>
Cc: ***@***.***>
Subject: [LattePandaTeam/Docs] Cannot find Windows 10 disc image file for Sigma (Issue #88)


Hi guys,
Quick question? Where is the image for Windows 10 for the Sigma? It seems that there is only a Win 11 image. I was expecting to see something similar to the Delta:

[image]<https://user-images.githubusercontent.com/16543721/236356876-4552a5a3-9680-49ba-9e98-62089ba0c12e.png>

Thank you!

**Comment by wappler99** [comment]
Hi,
I have followed the Windows installation guide referenced above, but it specifically says:

"Download the Windows 11 disc image file of LattePanda Sigma."
"Unzip the Windows 11 disc image file. "

However, I do not want to install Windows 11, I want to install Windows 10.

Can you please let me know where I can find the Windows 10 image for Sigma?

Thank you!

**Comment by LattePanda** [comment]
Hi,

We only released windows 11 image for LattePanda Sigma. You can install windows 10 on your Sigma. But pls note, Sigma uses intel i5-1340P Processor, which has P-core and E-core. There may be some bug when running win10.



***@***.***
 Best Regards,


Business Development

LattePanda Team

A: Rm 602, Puruan Bld.,No.2 Boyun Rd, Pudong, Shanghai | 201203 P.R.China

W: www.lattepanda.com<http://www.lattepanda.com/>


________________________________
发件人: wappler99 ***@***.***>
发送时间: Tuesday, May 9, 2023 4:45:00 PM
收件人: LattePandaTeam/Docs ***@***.***>
抄送: LattePanda ***@***.***>; Comment ***@***.***>
主题: Re: [LattePandaTeam/Docs] Cannot find Windows 10 disc image file for Sigma (Issue #88)


Hi,
I have followed the Windows installation guide referenced above, but it specifically says:

"Download the Windows 11 disc image file of LattePanda Sigma."
"Unzip the Windows 11 disc image file. "

However, I do not want to install Windows 11, I want to install Windows 10.

Can you please let me know where I can find the Windows 10 image for Sigma?

Thank you!

―
